# Generated by Django 2.2.24 on 2021-12-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('realName', models.CharField(max_length=15)),
                ('nickName', models.CharField(blank=True, default='', max_length=50)),
                ('sex', models.CharField(max_length=2)),
                ('birthday', models.DateTimeField()),
                ('avatar', models.URLField()),
                ('mother', models.IntegerField(max_length=10)),
                ('father', models.IntegerField(max_length=10)),
                ('children', models.TextField()),
                ('forebears', models.TextField()),
                ('lastLogin', models.DateTimeField()),
                ('idCard', models.CharField(max_length=18)),
                ('openId', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
